Enrollment
dline-code/rejuma-admin-front pull request #2
Opened 2022-11-21 18:06 UTC by EduardoPanzo

student enrollments and a context that seeks all the necessary data for this feat

2022-11-24 19:42 UTC, jgoncalves8080 reviewed
Seguir as recomendações deste arquivo para nomenclatura dos títlos de PR e commit's

2022-11-24 19:52 UTC, jgoncalves8080 requested changes

2022-11-24 19:52 UTC, jgoncalves8080 commented on src/contexts/AppointmentContext.jsx
> +  const completeApplicantAppointment = () => {
Qual a finalidade desta função? Só pra imprimir no console mesmo?

2022-11-24 19:52 UTC, jgoncalves8080 commented on src/contexts/RecordsContext.jsx
> +  const getUsersKind = async () => {
Colocar dentro de uma pasta service, conforme em outros componentes/views, e fazer lá a consulta.
Fazer a chamada aqui, posteriormente

2022-11-24 19:52 UTC, jgoncalves8080 commented on src/contexts/RecordsContext.jsx
> +    //const courses = await getCourses()
Senão for necessário, remover.

2022-11-24 19:52 UTC, jgoncalves8080 commented on src/views/matriculas/index.js
> +            {/* <div className="mb-40">
Que tal remover?

2022-11-24 19:52 UTC, jgoncalves8080 commented on src/views/matriculas/new/index.js
> +          tipoUsuarioId: 'beb7ad3d-3edf-4078-9f7b-0f098dab3679',
Porque estes id's são estáticos?

2022-11-24 19:52 UTC, jgoncalves8080 commented on src/views/matriculas/new/index.js
> +        const response = await api.post(`/matricula/post`, {
Fazer a busca em `/services`

2022-11-24 19:52 UTC, jgoncalves8080 commented on src/views/matriculas/new/step3/index.js
> +  const cursos = [
Que tal uma busca na api pra pegar estes dados?

2023-01-05 09:09 UTC, Antoniopedromuteka reviewed
finalizado...

2023-01-05 09:09 UTC, Antoniopedromuteka commented on src/views/matriculas/index.js
>              <CTable align="middle" className="mb-0 border" hover responsive>
penso que a tabela seria um componente e passarias as demais props

2023-01-05 09:09 UTC, Antoniopedromuteka commented on src/views/matriculas/new/index.js
> +  const [, setStepWizard] = useState(null)
use sempre custom hooks para evitar declarar states e funcões directamente nos próprios componentes. Apenas uma dica para melhor organização...

2023-01-05 09:09 UTC, Antoniopedromuteka commented on src/views/matriculas/new/step3/index.js
> +      <CTable align="middle" className="mb-0 border" hover responsive>
Mesma coisa teria um componente table bro...

2023-01-09 14:20 UTC, jgoncalves8080 approved these changes

2023-01-09 14:31 UTC, merged