feat: adicionando o crud de disciplinas
dline-code/rejuma-admin-front pull request #7
Opened 2022-12-19 12:18 UTC by Antoniopedromuteka

2022-12-20 19:07 UTC, eduardojpanzo commented on src/views/disciplinas/components/SaveTreatmentForm.js
> +        {errors.nome && <span>Este campo é Obrigatório</span>}
porque não defines a mensagem no required:"Campo obrigatório" e no span apenas mostre com <span>{errors.nome.message}</span>

2022-12-20 19:07 UTC, eduardojpanzo commented on src/views/disciplinas/components/SaveTreatmentForm.js
> +          <CFormInput id="description" placeholder="Descrição da disciplina" />
A descrição da disciplina pode ser vázia?, não tem nenhuma validação

2022-12-20 19:07 UTC, eduardojpanzo commented on src/views/disciplinas/index.js
>      setIsModalOpen(true)
não vejo nenhuma acção diferente entre criar uma disciplina e editar uma

2022-12-20 19:13 UTC, Antoniopedromuteka commented on src/views/disciplinas/index.js
>      setIsModalOpen(true)
Não tem função na api.

2022-12-20 19:13 UTC, Antoniopedromuteka commented on src/views/disciplinas/components/SaveTreatmentForm.js
> +          <CFormInput id="description" placeholder="Descrição da disciplina" />
não há descrição na api

2022-12-20 19:14 UTC, Antoniopedromuteka commented on src/views/disciplinas/components/SaveTreatmentForm.js
> +        {errors.nome && <span>Este campo é Obrigatório</span>}
vou resolver já mano.

2022-12-20 21:57 UTC, ggenilson commented on src/views/disciplinas/components/SaveTreatmentForm.js
>          <div style={{ display: 'flex', gap: 12 }}>
Não sei como está sendo o padrão de estilização aqui neste projeto, mas penso que deves modificar aqui. Se é Tailwind, que faças da forma do Tailwind. Se for Reactstrap, que assim também o faças.

2022-12-20 21:59 UTC, ggenilson commented on src/views/disciplinas/components/SaveTreatmentForm.js
> +        {errors.nome && <span>Este campo é Obrigatório</span>}
Evitar fazer a mistura de Inglês e Português na declaração de variáveis, funções, etc. Seguir um único padrão, que aqui no caso é Inglês.

2022-12-20 22:00 UTC, ggenilson commented on src/views/disciplinas/components/SaveTreatmentForm.js
>          <div style={{ display: 'flex', gap: 12 }}>
Verificar css aqui também.

2022-12-20 22:04 UTC, ggenilson commented on src/views/disciplinas/components/SaveTreatmentForm.js
> +      <CButton disabled={loading || false} type="submit">
Esta condição está meio estranha. Poderia justificar o porquê do **|| false** ?

2022-12-20 22:05 UTC, ggenilson commented on src/views/disciplinas/components/SaveTreatmentForm.js
>          {loading && <CSpinner component="span" size="sm" variant="grow" aria-hidden="true" />}
Estes tipos de verificações não são recomendadas, porque apresentam comportamentos inesperados.
** {loading ? <CSpinner component="span" size="sm" variant="grow" aria-hidden="true" /> : null}**
Acho que ficaria mais em conta dessa maneira.

2022-12-20 22:08 UTC, ggenilson commented on src/views/disciplinas/hooks/useFilterSubject.js
> +    console.log(value)
Evitar commitar código com console.log()

2022-12-20 23:54 UTC, ggenilson commented on src/views/disciplinas/hooks/useFilterSubject.js
> +  const [filteredData, setFilteredData] = useState([])
Não acho que seja necessário criar state para o `filteredData`. Ele pode ser uma variável normal, e aí você preenche sempre que o `filterBy` for selecionado.

Algo assim:

`const filteredData = filterBy.length ? chama_a_funcao_de_pesquisa : [] `

2022-12-20 23:55 UTC, ggenilson commented on src/views/disciplinas/hooks/useFilterSubject.js
> +    console.log(filterBy)
Eliminar console.log()

2022-12-20 23:58 UTC, ggenilson commented on src/views/disciplinas/index.js
> +                  <CFormSelect name="selectSm" id="SelectLm" onChange={handlefilterBy}>
Acho que poderias já automatizar este select. Imaginemos que você vá utilizar ele outra vez em um outro local. Terias que fazer novamente um map???

Cria  um componente para este select, onde passas um data que será um array com labels e values, e ele internamente fará o preenchimento dos dados no select.

2022-12-20 23:58 UTC, ggenilson commented on src/views/disciplinas/index.js
>                        style={{ width: '80%' }}
O css novamente.

2022-12-21 00:00 UTC, ggenilson commented on src/views/disciplinas/index.js
> +                  ? subjectData?.map(({ id, nome }, idx) => (
O JSX que você retorna para o subjectData é o mesmo que o filteredData, a diferença está somente nos dados.
Poderias criar um componente separado, onde só passas o data, e ele renderiza já o JSX com base no data. Para evitar estas repetições de JSX.

2022-12-21 00:02 UTC, ggenilson requested changes
Muteka, fiz alguns comentários aqui, poderia começar a trabalhar nelas já, vlw.

2022-12-22 09:58 UTC, ggenilson commented on src/views/disciplinas/components/SaveTreatmentForm.js
> +        <span className="text-danger text-sm">{errors.nome?.message}</span>
E se não tiver erro?

2022-12-22 10:27 UTC, Antoniopedromuteka commented on src/views/disciplinas/components/SaveTreatmentForm.js
> +        <span className="text-danger text-sm">{errors.nome?.message}</span>
esquecime-me desse detalhe ainda estou alterando...
também o mecanismo de busca.

2022-12-22 12:19 UTC, EduardoPanzo approved these changes

2022-12-22 22:15 UTC, ggenilson approved these changes

2023-01-09 14:20 UTC, jgoncalves8080 approved these changes

2023-01-09 14:20 UTC, merged